language: generic

sudo: required

services:
  - docker

after_success:
  - docker build -t gksrlfw/mp3-downloader-server ./server
  - docker build -t gksrlfw/mp3-downloader-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push gksrlfw/mp3-downloader-server
  - docker push gksrlfw/mp3-downloader-nginx
