language: generic

sudo: required

services:
  - docker

after_success:
  - docker build -t gksrlfw/mb-server-server ./server
  - docker build -t gksrlfw/mb-server-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push gksrlfw/mb-server-server
  - docker push gksrlfw/mb-server-nginx
